title: joel
description: >- # this means to ignore newlines until "baseurl:"
  i’m joel, a teenage developer who is interested in open source and decentralisation. i enjoy automating as much as i can with code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
header_pages:
  - keys/keys.md
  - contact.md
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    discord: "636543487600492545"
    github: jyooru
    keybase: jyooru
    reddit: jyooru
    repository: https://github.com/jyooru/website
    twitter: jyooru
plugins:
  - jekyll-feed
  - jekyll-remote-theme
feed:
  path: /
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
