title: joel
description: >- # this means to ignore newlines until "baseurl:"
  i’m joel, a teenage developer interested in cybersecurity, open source and decentralisation. i enjoy automating as much as i can with code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
header_pages:
  - keys/keys.md
  - contact.md
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    discord: "636543487600492545"
    github: jyooru
    keybase: jyooru
    reddit: jyooru
    repository: https://github.com/jyooru/website
    twitter: jyooru
plugins:
  - jekyll-feed
  - jekyll-remote-theme
feed:
  path: /
exclude:
  - README.md
  - LICENSE
